### PR TITLE
Unused pin support

### PR DESCRIPTION
**Pull request by stromnet**
Hi,

I added some experimental unused-pin support as discussed in #9.
I haven't tested this on hardware yet, I just wanted to push and see what you think about the solution (both cfg and impl)?
The config should have "unused: [D0,D1,D2]" (or other list variant)

Johan

### CODE REVIEW

**Comment by stromnet** [comment]
Tested and works. Had to add some delay between writing the ddr/port registers, and reading back the pin register, or the pin bit's where read as low (disabling the pull-up again).

A single nop wasn't sufficient either, as hinted by the datasheets. 4 standalone nop's wasn't enough either (which has the same resulting code size as current solution). The current solution adds 32 cycles, which seems to be enough on my test board with about 1cm of trace between the chip and the floating pin headers.

**Comment by smurfix** [comment]
Thanks. Looks good. I added a couple of (minor) review comments to your patch.

**Comment by stromnet** [comment]
Fixed all but the UNUSED_PIOS thing with the semicolons, see comment

**Comment by smurfix** [comment]
On 23.11.2015 23:30, Johan Ström wrote:

> Fixed all but the UNUSED_PIOS thing with the semicolons, see comment
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/M-o-a-T/owslave/pull/10#issuecomment-159088536.
> 
> Thanks, great, will merge ASAP

## 

-- Matthias Urlichs

**Comment by stromnet** [comment]
Ping @smurfix... :) Fyi this has been working flawlessly for a year now.

**Comment by smurfix** [comment]
better late than never ;-)

**Pull request merged**
